Traceback (most recent call last):
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1653, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_common.py", line 480, in wrapper
    raise raise_from(err, None)
  File "<string>", line 3, in raise_from
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_common.py", line 478, in wrapper
    return fun(self)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1695, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_common.py", line 813, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_common.py", line 801, in cat
    with _open(fname) as f:
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_common.py", line 765, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/67158/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/__init__.py", line 719, in create_time
    self._create_time = self._proc.create_time()
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1653, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1863, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1660, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=67158)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ml/wine/airflow/myenv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 481, in webserver
    gunicorn_master_proc = psutil.Process(gunicorn_master_proc_pid)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=67158)
/opt/ml/wine/airflow/myenv/lib/python3.8/site-packages/airflow/configuration.py:276: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(sqlite3.sqlite_version) < StrictVersion(min_sqlite_version):
